version: '2'

services:
  jenkins:
    image: jenkins/jenkins
    volumes:
      - ./dados_jenkins:/var/jenkins_home
    # environment:
    #   - PORT=3000
    # command:
    #   bash "echo oi"
    # depends_on:
    #   - servico
    ports:
      - 8080:8080
      - 50000:50000
      
  # outro_servico: